fix: add missing appstream data for flatpak builder (#3911)
Commit updates appstream data to pass strict validation, which is necessary to build new Flatpak versions.

Flatpak builder added strict validation and requires "developer" information [1] to be provided.

Build error:

```
Run docker run --rm --privileged \
+ flatpak-builder-lint --exceptions repo repo
{
    "errors": [
        "appstream-missing-developer-name"
    ],
    "warnings": [
        "appstream-screenshot-missing-caption"
    ],
    "info": [
        "appstream-screenshot-missing-caption: One or more screenshots
are missing captions in the Metainfo file",
        "appstream-missing-developer-name: No developer tag found in
Metainfo file"
    ],
    "message": "Please consult the documentation at
https://docs.flathub.org/docs/for-app-authors/linter"
}
error: Recipe `validate-build` failed with exit code 1
```

For good measure, captions for the provided screenshots are added.

After changes made, `appstreamcli validate` only mentions issue with uppercase cid component which should be kept as is:

```sh
$ appstreamcli validate --pedantic data/appdata/org.flameshot.Flameshot.metainfo.xml
P: org.flameshot.Flameshot:7: cid-contains-uppercase-letter org.flameshot.Flameshot

✔ Validation was successful: pedantic: 1
```

[1]: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines#developer-name